### ISSUE TITLE
Reminder system is broken

### ISSUE THREAD

**Issue by alexthemaster** [penfoldium/penfoldbot#4]
The reminder system might currently not work as intended (getting reminders twice, reminders not getting deleted etc.) because of a known bug in Klasa. 

We will keep you updated.

**Comment by YoshiFan13** [comment]
I don't think this is relevant anymore. I used to be hit by these issues before but now everything seems to work properly on my side.

**Comment by alexthemaster** [comment]
It looks like the system has been fixed in Klasa recently.

Will re-open this issue if necessary.
